### ISSUE TITLE
Add Remote Logging for bots

### ISSUE THREAD

**Issue by itsthejoker** [itsthejoker/TranscribersOfReddit#1]
Currently we have a key set up for Sentry, but it only allows one team member to access it. This is a problem going forward, so the next contender worth looking at is bugsnag.

**Comment by TheLonelyGhost** [comment]
If we go the self-hosted route, we could also look at [Errbit](https://errbit.com/docs/master/) with the [Airbrake client for Python](https://pypi.python.org/pypi/airbrake)

**Comment by itsthejoker** [comment]
Right now we need to avoid the self hosted route since both the bot and the logging would be on the same network. That way we'd get no warning if the internet went out, which has already happened once since I've moved.

Once we're on DigitalOcean or somewhere else, this is much less of an issue.

**Comment by itsthejoker** [comment]
Current branch: https://github.com/itsthejoker/TranscribersOfReddit/tree/the-logging-update
